services:
- type: web
  name: frontend
  runtime: docker
  repo: https://github.com/Devinekyle/Mandatory_Training_APP/tree/3a73dfe5b6c4882ceb2985e60ba5d2d9452ec440/mandatory-training
  plan: free
  region: oregon
  rootDir: frontend
  healthCheckPath: /
- type: web
  name: backend
  runtime: docker
  repo: https://github.com/Devinekyle/Mandatory_Training_APP/tree/3a73dfe5b6c4882ceb2985e60ba5d2d9452ec440/back-end
  rootDir: backend
  healthCheckPath: /
databases:
- name: prod
  databaseName: utm_tool
  user: app_user
