services:
- type: web
  name: frontend
  runtime: docker
  repo: https://github.com/Devinekyle/Mandatory_Training_APP.git
  plan: free
  region: oregon
  rootDir: ./mandatory-training/
  dockerfilePath: ./dockerfile
  healthCheckPath: /
  envVars:
  - key: PORT
    value: 3000
- type: web
  name: backend
  runtime: static
  staticPublishPath: ./build
  repo: https://github.com/Devinekyle/Mandatory_Training_APP.git
  rootDir: ./back-end/
  healthCheckPath: /
  buildFilter:
      paths:
      - src/**/*.js
      ignoredPaths:
      - src/**/*.test.js
  headers:
    - path: /*
      name: X-Frame-Options
      value: sameorigin
  routes:
    - type: rewrite
      source: /*
      destination: /index.html
  envVars:
  - key: PORT
    value: 4000
databases:
- name: prod
  plan: free
  databaseName: utm_tool
  user: app_user
